import { SocialCharacterization, SocialCharacterizationStats } from "./social-characterization-types"

// ─── Datos de Caracterización Social (basados en CSV real) ─────────────

export const mockSocialCharacterizations: SocialCharacterization[] = [
  {
    id: "sc-001",
    encuestadoId: "F01",
    propertyId: "p1",
    fecha: "2025-12-09",
    zonaAeroportuaria: "Indirecta",
    tratamientoUrbanistico: "Consolidación",
    inAEDAF: true,
    nombreMorador: "Carlos Ramirez",
    tipoMorador: "Propietario",
    direccion: "Calle 22i # 112B-33",
    edad: 56,
    percepcionEntorno: {
      ruido: "Muy negativo",
      contaminacionAire: "Muy negativo",
      traficoVehicular: "Muy negativo",
      traficoCarga: "Muy negativo",
    },
    oportunidades: {
      empleo: "En desacuerdo",
      valorPredios: "En desacuerdo",
      beneficiosGenerales: "En desacuerdo",
    },
    actividadPredioUltimoAno: "Ha recibido ofertas de compra (o el dueño)",
    probabilidadAsociacionVecinos: "Nada probable",
    disposicion: {
      intencionPrincipal: "Quedarme en mi predio (no vender)",
      preferenciaSiVende: "",
      interesAsociacion: "No me interesa",
      aspectosAtractivos: {
        infoClaraBeneficios: true,
        mayorGananciaVentaConjunta: false,
        ingresosPeriodicos: false,
        pagoUnico: false,
        opcionesReubicacion: false,
        otraOpcion: "",
      },
      tiempoDecision: "No lo sé",
      tamanoGrupo: "Me sentiría incómodo asociándome con otros vecinos",
    },
    herramientasDigitales: {
      comodidadUso: "De acuerdo",
      preferenciaApoyo: "De acuerdo",
      necesidadReunionesPresenciales: "De acuerdo",
    },
    barreras: {
      faltaInformacion: "Mucho",
      desconfianza: "Mucho",
      faltaClaridad: "Mucho",
      problemasLegales: "Mucho",
      esperaMasUnAno: "Mucho",
      opinionFamilia: "Mucho",
      dependenciaIngresos: "Mucho",
      relacionesSociales: "Mucho",
      faltaExperiencia: "Mucho",
      temorReubicacion: "Mucho",
      temorProyectoNoRentable: "Mucho",
    },
    factoresMotivadores: {
      cercaniaRedApoyo: "Muy importante",
      mejorarIngresos: "Muy importante",
      mejorarCalidadVivienda: "Muy importante",
      claridadJuridica: "Muy importante",
      actividadesEconomicas: "Muy importante",
    },
    actitudesCambio: {
      prefiereNadaCambie: "Muy en desacuerdo",
      dispuestoConsiderarCambios: "Muy de acuerdo",
      preocupaDecisionSinResidentes: "Muy de acuerdo",
      deseaParticipar: "Muy de acuerdo",
    },
    preferenciasDeclaradas: {
      ficha1: "A",
      ficha2: "A",
      ficha3: "A",
      ficha4: "A",
      ficha5: "A",
      ficha6: "A",
    },
  },
  {
    id: "sc-002",
    encuestadoId: "F02",
    propertyId: "p2",
    fecha: "2025-12-09",
    zonaAeroportuaria: "Indirecta",
    tratamientoUrbanistico: "Renovación",
    inAEDAF: true,
    nombreMorador: "Maria Gonzalez",
    tipoMorador: "Propietario",
    direccion: "Carrera 97 # 20C-28",
    edad: 69,
    percepcionEntorno: {
      ruido: "Negativo",
      contaminacionAire: "Muy negativo",
      traficoVehicular: "Positivo",
      traficoCarga: "Negativo",
    },
    oportunidades: {
      empleo: "Muy de acuerdo",
      valorPredios: "Muy de acuerdo",
      beneficiosGenerales: "Muy de acuerdo",
    },
    actividadPredioUltimoAno: "Ambas",
    probabilidadAsociacionVecinos: "No sabe",
    disposicion: {
      intencionPrincipal: "Vender y mudarme a otro lugar",
      preferenciaSiVende: "Comprar algo en otro sector",
      interesAsociacion: "Sí me interesa",
      aspectosAtractivos: {
        infoClaraBeneficios: true,
        mayorGananciaVentaConjunta: true,
        ingresosPeriodicos: true,
        pagoUnico: false,
        opcionesReubicacion: false,
        otraOpcion: "",
      },
      tiempoDecision: "Menos de 6 meses",
      tamanoGrupo: "Solo con 2 o 3 vecinos cercanos",
    },
    herramientasDigitales: {
      comodidadUso: "Muy de acuerdo",
      preferenciaApoyo: "Muy de acuerdo",
      necesidadReunionesPresenciales: "Muy de acuerdo",
    },
    barreras: {
      faltaInformacion: "Mucho",
      desconfianza: "Mucho",
      faltaClaridad: "Mucho",
      problemasLegales: "Nada",
      esperaMasUnAno: "Mucho",
      opinionFamilia: "Poco",
      dependenciaIngresos: "Mucho",
      relacionesSociales: "Algo",
      faltaExperiencia: "Algo",
      temorReubicacion: "Mucho",
      temorProyectoNoRentable: "Mucho",
    },
    factoresMotivadores: {
      cercaniaRedApoyo: "Algo importante",
      mejorarIngresos: "Muy importante",
      mejorarCalidadVivienda: "Muy importante",
      claridadJuridica: "Muy importante",
      actividadesEconomicas: "Muy importante",
    },
    actitudesCambio: {
      prefiereNadaCambie: "Muy en desacuerdo",
      dispuestoConsiderarCambios: "Muy de acuerdo",
      preocupaDecisionSinResidentes: "Muy en desacuerdo",
      deseaParticipar: "Muy de acuerdo",
    },
    preferenciasDeclaradas: {
      ficha1: "B",
      ficha2: "A",
      ficha3: "A",
      ficha4: "A",
      ficha5: "A",
      ficha6: "A",
    },
  },
  {
    id: "sc-003",
    encuestadoId: "F03",
    propertyId: "p3",
    fecha: "2025-12-09",
    zonaAeroportuaria: "Indirecta",
    tratamientoUrbanistico: "Renovación",
    inAEDAF: true,
    nombreMorador: "Ana Martinez",
    tipoMorador: "Propietario",
    direccion: "Carrera 97B # 20-61",
    edad: 76,
    percepcionEntorno: {
      ruido: "Negativo",
      contaminacionAire: "Negativo",
      traficoVehicular: "Negativo",
      traficoCarga: "Muy negativo",
    },
    oportunidades: {
      empleo: "Muy de acuerdo",
      valorPredios: "Muy de acuerdo",
      beneficiosGenerales: "De acuerdo",
    },
    actividadPredioUltimoAno: "Ninguna",
    probabilidadAsociacionVecinos: "Nada probable",
    disposicion: {
      intencionPrincipal: "Quedarme en mi predio (no vender)",
      preferenciaSiVende: "",
      interesAsociacion: "Tal vez, si los beneficios están claros",
      aspectosAtractivos: {
        infoClaraBeneficios: true,
        mayorGananciaVentaConjunta: false,
        ingresosPeriodicos: false,
        pagoUnico: true,
        opcionesReubicacion: true,
        otraOpcion: "",
      },
      tiempoDecision: "Entre 1 y 3 años",
      tamanoGrupo: "No lo sé",
    },
    herramientasDigitales: {
      comodidadUso: "De acuerdo",
      preferenciaApoyo: "Muy de acuerdo",
      necesidadReunionesPresenciales: "De acuerdo",
    },
    barreras: {
      faltaInformacion: "Mucho",
      desconfianza: "Mucho",
      faltaClaridad: "Mucho",
      problemasLegales: "Nada",
      esperaMasUnAno: "Mucho",
      opinionFamilia: "Algo",
      dependenciaIngresos: "Algo",
      relacionesSociales: "Nada",
      faltaExperiencia: "Mucho",
      temorReubicacion: "Algo",
      temorProyectoNoRentable: "Algo",
    },
    factoresMotivadores: {
      cercaniaRedApoyo: "Nada importante",
      mejorarIngresos: "Muy importante",
      mejorarCalidadVivienda: "Algo importante",
      claridadJuridica: "Algo importante",
      actividadesEconomicas: "Muy importante",
    },
    actitudesCambio: {
      prefiereNadaCambie: "En desacuerdo",
      dispuestoConsiderarCambios: "De acuerdo",
      preocupaDecisionSinResidentes: "Muy de acuerdo",
      deseaParticipar: "De acuerdo",
    },
    preferenciasDeclaradas: {
      ficha1: "A",
      ficha2: "A",
      ficha3: "A",
      ficha4: "A",
      ficha5: "A",
      ficha6: "A",
    },
  },
  {
    id: "sc-004",
    encuestadoId: "F05",
    propertyId: "p5",
    fecha: "2025-12-09",
    zonaAeroportuaria: "Indirecta",
    tratamientoUrbanistico: "Renovación",
    inAEDAF: true,
    nombreMorador: "Pedro Lopez",
    tipoMorador: "Propietario",
    direccion: "Calle 20B #97B-42",
    edad: 62,
    percepcionEntorno: {
      ruido: "Ni positivo ni negativo",
      contaminacionAire: "Negativo",
      traficoVehicular: "Negativo",
      traficoCarga: "Negativo",
    },
    oportunidades: {
      empleo: "De acuerdo",
      valorPredios: "De acuerdo",
      beneficiosGenerales: "De acuerdo",
    },
    actividadPredioUltimoAno: "Ambas",
    probabilidadAsociacionVecinos: "Algo probable",
    disposicion: {
      intencionPrincipal: "Vender y mudarme a otro lugar",
      preferenciaSiVende: "No responde",
      interesAsociacion: "Sí me interesa",
      aspectosAtractivos: {
        infoClaraBeneficios: true,
        mayorGananciaVentaConjunta: true,
        ingresosPeriodicos: true,
        pagoUnico: false,
        opcionesReubicacion: false,
        otraOpcion: "",
      },
      tiempoDecision: "Menos de 6 meses",
      tamanoGrupo: "Solo con 2 o 3 vecinos cercanos",
    },
    herramientasDigitales: {
      comodidadUso: "Muy de acuerdo",
      preferenciaApoyo: "De acuerdo",
      necesidadReunionesPresenciales: "Ni acuerdo ni desacuerdo",
    },
    barreras: {
      faltaInformacion: "Mucho",
      desconfianza: "Algo",
      faltaClaridad: "Mucho",
      problemasLegales: "Algo",
      esperaMasUnAno: "Mucho",
      opinionFamilia: "Nada",
      dependenciaIngresos: "Mucho",
      relacionesSociales: "Poco",
      faltaExperiencia: "Algo",
      temorReubicacion: "Poco",
      temorProyectoNoRentable: "Mucho",
    },
    factoresMotivadores: {
      cercaniaRedApoyo: "Algo importante",
      mejorarIngresos: "Importante",
      mejorarCalidadVivienda: "Importante",
      claridadJuridica: "Importante",
      actividadesEconomicas: "Importante",
    },
    actitudesCambio: {
      prefiereNadaCambie: "Muy en desacuerdo",
      dispuestoConsiderarCambios: "Muy de acuerdo",
      preocupaDecisionSinResidentes: "De acuerdo",
      deseaParticipar: "Muy de acuerdo",
    },
    preferenciasDeclaradas: {
      ficha1: "B",
      ficha2: "B",
      ficha3: "B",
      ficha4: "B",
      ficha5: "B",
      ficha6: "B",
    },
  },
  {
    id: "sc-005",
    encuestadoId: "F06",
    propertyId: "p6",
    fecha: "2025-12-09",
    zonaAeroportuaria: "Directa",
    tratamientoUrbanistico: "Renovación",
    inAEDAF: true,
    nombreMorador: "Laura Sanchez",
    tipoMorador: "Propietario",
    direccion: "Calle 23G Bis # 96g-92",
    edad: 59,
    percepcionEntorno: {
      ruido: "Positivo",
      contaminacionAire: "Positivo",
      traficoVehicular: "Positivo",
      traficoCarga: "Positivo",
    },
    oportunidades: {
      empleo: "De acuerdo",
      valorPredios: "Muy en desacuerdo",
      beneficiosGenerales: "De acuerdo",
    },
    actividadPredioUltimoAno: "Ambas",
    probabilidadAsociacionVecinos: "Algo probable",
    disposicion: {
      intencionPrincipal: "Quedarme en mi predio (no vender)",
      preferenciaSiVende: "",
      interesAsociacion: "No responde",
      aspectosAtractivos: {
        infoClaraBeneficios: true,
        mayorGananciaVentaConjunta: false,
        ingresosPeriodicos: false,
        pagoUnico: false,
        opcionesReubicacion: false,
        otraOpcion: "",
      },
      tiempoDecision: "No lo sé",
      tamanoGrupo: "Con la manzana completa",
    },
    herramientasDigitales: {
      comodidadUso: "En desacuerdo",
      preferenciaApoyo: "En desacuerdo",
      necesidadReunionesPresenciales: "De acuerdo",
    },
    barreras: {
      faltaInformacion: "Algo",
      desconfianza: "Poco",
      faltaClaridad: "Poco",
      problemasLegales: "Algo",
      esperaMasUnAno: "Nada",
      opinionFamilia: "Mucho",
      dependenciaIngresos: "Poco",
      relacionesSociales: "Mucho",
      faltaExperiencia: "Nada",
      temorReubicacion: "Mucho",
      temorProyectoNoRentable: "Mucho",
    },
    factoresMotivadores: {
      cercaniaRedApoyo: "Importante",
      mejorarIngresos: "Importante",
      mejorarCalidadVivienda: "Importante",
      claridadJuridica: "Importante",
      actividadesEconomicas: "Importante",
    },
    actitudesCambio: {
      prefiereNadaCambie: "De acuerdo",
      dispuestoConsiderarCambios: "De acuerdo",
      preocupaDecisionSinResidentes: "Muy de acuerdo",
      deseaParticipar: "Muy de acuerdo",
    },
    preferenciasDeclaradas: {
      ficha1: "A",
      ficha2: "A",
      ficha3: "A",
      ficha4: "A",
      ficha5: "A",
      ficha6: "A",
    },
  },
]

// ─── Estadísticas Agregadas ────────────────────────────────────────────

export const socialCharacterizationStats: SocialCharacterizationStats = {
  totalEncuestas: 56,
  promedioEdad: 65.2,

  distribucionZona: {
    directa: 34,
    indirecta: 18,
    noAplica: 4,
  },

  distribucionIntencion: {
    quedarse: 32,
    vender: 18,
    noResponde: 6,
  },

  interesAsociacion: {
    siMeInteresa: 12,
    talVez: 18,
    indiferente: 6,
    noMeInteresa: 17,
    otraOpcion: 3,
  },

  barrerasPrincipales: [
    {
      nombre: "Falta de información",
      intensidadPromedio: 3.4,
      porcentajeAlto: 72,
    },
    {
      nombre: "Desconfianza para trabajar en conjunto",
      intensidadPromedio: 3.1,
      porcentajeAlto: 65,
    },
    {
      nombre: "Falta de claridad en condiciones",
      intensidadPromedio: 3.3,
      porcentajeAlto: 70,
    },
    {
      nombre: "Temor a que proyecto no se concrete",
      intensidadPromedio: 3.2,
      porcentajeAlto: 68,
    },
    {
      nombre: "Tener que esperar más de un año",
      intensidadPromedio: 3.0,
      porcentajeAlto: 62,
    },
  ],

  factoresMotivadoresPrincipales: [
    {
      nombre: "Mejorar ingresos / estabilidad económica",
      importanciaPromedio: 4.6,
      porcentajeMuyImportante: 85,
    },
    {
      nombre: "Mejorar calidad de vivienda",
      importanciaPromedio: 4.4,
      porcentajeMuyImportante: 78,
    },
    {
      nombre: "Tener claridad jurídica sobre el predio",
      importanciaPromedio: 4.5,
      porcentajeMuyImportante: 82,
    },
    {
      nombre: "Mantener cercanía a red de apoyo",
      importanciaPromedio: 3.8,
      porcentajeMuyImportante: 58,
    },
    {
      nombre: "Mantener actividades económicas",
      importanciaPromedio: 4.2,
      porcentajeMuyImportante: 74,
    },
  ],

  percepcionPromedioEntorno: {
    ruido: 1.8, // Escala 1-5 donde 1 es muy negativo
    contaminacion: 1.7,
    trafico: 1.9,
    traficoCarga: 1.6,
  },

  distribucionTiempoDecision: {
    menosSeisMeses: 28,
    seisADoce: 12,
    unoATres: 8,
    masTres: 3,
    noSabe: 5,
  },
}
